### PR TITLE
Hi tech research: Translation update

### PR DESCRIPTION
**Pull request by Reiquard**

### CODE REVIEW

**Comment by jptrrs** [comment]
My man! It's awesome you stepped up to updating the translation! Thanks!
Unfortunately there were more to come. Check the english keys file on the master branch (I just merged the HiTechResearch branch). Its pratically done.

**Comment by Reiquard** [comment]
Is there any possibility (other than spawning via dev mode) to have TechDrive at the player's disposal?
If the answer is "yes", then I have the following questions:

 - The drives are named after books:
`<BookTheory>{0} Theory</BookTheory>`
`<BookDatabase>{0} Database</BookDatabase>`
Should I rename them to fit the meaning?

 - Also, I couldn't find an acceptable place (such as a book shelf) to store the drives other than a standard stockpile. Does this place exist?

**Comment by Reiquard** [comment]
I couldn't find where [StuffCategories](https://github.com/jptrrs/HumanResources/blob/master/Defs/StuffCategories.xml) are displayed in the game (I believe that these lines are for internal use).
Does it need to be translated?

P.S.
While investigating this question, I found that this [method](https://github.com/jptrrs/HumanResources/blob/af7da71d3ab0ba982752e53ee7b3e6538d4f9152/Source/Harmony/Compatibility/MaterialFilter_Patch.cs#L17) tries to operate on the [commented-out](https://github.com/jptrrs/HumanResources/blob/af7da71d3ab0ba982752e53ee7b3e6538d4f9152/Defs/StuffCategories.xml#L4) string

```
if (stuffToFilter.defName == "Technic")
```

**Comment by jptrrs** [comment]
> Is there any possibility (other than spawning via dev mode) to have TechDrive at the player's disposal?

Yes. They can be bought or earned as rewards, just like books.

> If the answer is "yes", then I have the following questions:
> 
>     * The drives are named after books:
>       `<BookTheory>{0} Theory</BookTheory>`
>       `<BookDatabase>{0} Database</BookDatabase>`
>       Should I rename them to fit the meaning?

Internally, the drives are merely a kind of book. I intend to keep the naming convention, as if the contents of books and drives are equivalent. Only the physical form changes, and with that, the steps to handle them too.

>     * Also, I couldn't find an acceptable place (such as a book shelf) to store the drives other than a standard stockpile. Does this place exist?

Yup, until you are able to scan them on a network terminal, they'll behave just like a regular item. In fact, on the stockpile filter, you'll find them under "Items". But I must say this isn't working yet, currently pawns seem to be having some difficulty finding them to scan.

**Comment by jptrrs** [comment]
> I couldn't find where [StuffCategories](https://github.com/jptrrs/HumanResources/blob/master/Defs/StuffCategories.xml) are displayed in the game (I believe that these lines are for internal use).

They are displayed on the recipe filters.

> Does it need to be translated?

Yes!
> 
> P.S.
> While investigating this question, I found that this [method](https://github.com/jptrrs/HumanResources/blob/af7da71d3ab0ba982752e53ee7b3e6538d4f9152/Source/Harmony/Compatibility/MaterialFilter_Patch.cs#L17) tries to operate on the [commented-out](https://github.com/jptrrs/HumanResources/blob/af7da71d3ab0ba982752e53ee7b3e6538d4f9152/Defs/StuffCategories.xml#L4) string
> 
> ```
> if (stuffToFilter.defName == "Technic")
> ```

Glad you noticed that! That's a patch for compatibility with Material Filter, It would have cause havoc if I didn't correct it. Thanks again!

**Comment by Reiquard** [comment]
> They are displayed on the recipe filters.

On the recipe filters I see only [ThingCategories](https://github.com/jptrrs/HumanResources/blob/master/Defs/ThingCategories.xml) which are translated (while StuffCategories aren't)

**Comment by jptrrs** [comment]
> 
> 
> > They are displayed on the recipe filters.
> 
> On the recipe filters I see only [ThingCategories](https://github.com/jptrrs/HumanResources/blob/master/Defs/ThingCategories.xml) which are translated (while StuffCategories aren't)

Really? Hmm.. I guess I hacked those to show the thingCategories.... Maybe you're right and they don't actually appear anywhere. Maybe having actually separated stuffcategories for each techlevel allow me to get rid of the corresponding thingcategories altogether... Dunno, leave them untranslated then. It would be the same exact translation for the ThinCategories anyway, if needed I can just copy/paste.

**Comment by jptrrs** [comment]
Hello, Reiquard! How are you doing? I'm still polishing this damn mod... It's about complete now. 
Would you mind translating three more lines?
https://github.com/jptrrs/HumanResources/blob/master/Languages/Russian/Keyed/HumanResources_keys.xml

**Comment by Reiquard** [comment]
Done with those three lines.
And while making this translation, I noticed that there is a missing tip for research assignment

**"Left-click to assign for studying."**
screenshot1

**"Left-click to assign for documentation."**
screenshot2

**"Left-click to assign for research."** _**is missing.**_
screenshot3

However, after a left-click on a latter, a tip **"Left-click to unassign."** appears.
screenshot4

If this shouldn't be the case, here is the translation line:
ЛКМ - назначить для исследования

**Comment by jptrrs** [comment]
You're always good with the details! :-)
But this tip is meant for the assignments on the pawn's Tech tab, and it only ever displays techs that already have been researched. Research assignments are made only on the main Research menu, and when they're displayed on the pawn's tab the only possible action is to remove them.
Thanks anyway! It's always good to have an extra set of eyes watching for possible failures.
Cheers!

P.S.: What's the deal with Putin, Navalny and Ukraine?

**Comment by Reiquard** [comment]
I'm out of politics, but hope they are doing well ;]

**Comment by jptrrs** [comment]
:-D

**Pull request merged**
