### PR TITLE
[ResearchPal - Forked] support; Mlie's [Roads Of The Rim] support

### PR DESCRIPTION
**Pull request by Reiquard**
Added support for ResearchPal - Forked (at least at first glance it works fine).
Added support for continued by Mlie version of Roads Of The Rim mod.
Some translation corrections.

### CODE REVIEW

**Comment by Reiquard** [comment]
I may have been too hasty with the [ResearchPal - Forked] part - further testing showed that some recently implemented features are not available.
Despite that, the basic interaction of your mod and ResearchPal(Forked) remained without visible changes.

**Comment by jptrrs** [comment]
Its cool, since you already did the basics, I can depart from here to navigate into harder stuff! Thx!
If you figure something else, don't hesitate to update this PR, it might be useful.

**Comment by jptrrs** [comment]
I managed to get it working properly with ResearchPal - Forked. It's still missing some polish, but if you wanna help me test it out, check [this branch](/jptrrs/HumanResources/tree/forVinaLXsRPal).

**Comment by Reiquard** [comment]
I believe that all issues related to [_ResearchPal - Forked_] can be discussed here..
I spent some time testing it with HR, and have to say I didn't find any issues with the RP-F (aside from those functions that was turned off by your mod, such as drag and drop research nodes, Alt- and Shift- clicking to add to queue and the queue itself, which of course need to be disabled to work in conjunction with HR).

However, there are a few things related to HR that I want to mention:

During one game session, I started several new colonies. Opening the tab in subsequent colonies, I found an image of assigned pawn from the previous colony

screenshot28

Also, right-clicking that image doesn't remove the assignement of that otherworld pawn **NOR** the ones that are present on the map.
It doesn't remove the assignment (of _real_ pawns) **even** if I start a new colony under the new game session.
Right-clicking just sets/unsets to highlight the node with the blue frame.

Mods I used during testing:
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>unlimitedhugs.hugslib</li>
    <li>fluffy.modmanager</li>
    <li>vinalx.researchpalforked</li>
    <li>jpt.humanresources</li>

**Comment by jptrrs** [comment]
Thanks for testing!
I managed to solve the issue removing assignments by clicking on the main research tab. But what you say about the different colonies confuses me. Are you talking about different settlements on the same savegame, or did you start different games from the main menu? It it's the latter, then this is normal, the colonists and assignments should be from all maps at the same time.

**Comment by Reiquard** [comment]
Here are the actions to reproduce:

Main menu of the newly launched Rimworld => [New Colony] => [Next, Next, Generate, Next, Start] => [Research] tab => Assign a pawn to research some tech => [Esc, Esc] => [Quit to main menu] => [New Colony] => .. => [Research] tab => And here is a previously assigned pawn from another game.

..Although it disappears after reopening the tab.

Have to note also that this thing with reopening sometimes resets recently set assignments (this could be seen in ResearchPal or ResearchTree before too).

**Comment by jptrrs** [comment]
Ok, ok. That's just a cache that needed clearing on the game start. It didn't actually affect the assignments. Corrected for the next update.

**Pull request merged**
